### PR TITLE
Update French & Turkish translations

### PR DESCRIPTION
**Pull request by cardpuncher**
Please note there's a "quick save format" string in English at line 3,26. Shouldn't that be "quick safe format"? Can't wait for a test version now :-)

### CODE REVIEW

**Comment by PerditionC** [comment]
Test build available under releases - https://github.com/FDOS/format/releases/download/v0.92/format-092a-test2.zip   Set LANG=TR or LANG=FR (or LANG=EN) to see translations.  You can use kittenc to dump, edit, and attach again.

**Comment by PerditionC** [comment]
I will have to read through the source, but I think you are correct it should not be "quick save format", but maybe "safe quick format"?

**Comment by cardpuncher** [comment]
On 3.09.2024 21:31, Kenneth J Davis wrote:
> Test build available under releases - https://github.com/FDOS/format/ 
> releases/download/v0.92/format-092a-test2.zip <https://github.com/FDOS/ 
> format/releases/download/v0.92/format-092a-test2.zip> Set LANG=TR or 
> LANG=FR (or LANG=EN) to see translations. 

Thank you, but when I download the archive with Lynx, unpack it and then 
try to use it, everything is in English. This is under FreeDOS Test 2409 
under VirtualBox with one VM in French and another in Turkish (from the 
installation process). Doing an additional SET LANG=FR or TR doesn't 
change anything. What am I doing wrong?

**Comment by PerditionC** [comment]
there was just format.exe in the zip?  let me check, maybe I zipped the pre attached binary.

**Comment by PerditionC** [comment]
To help track down the issue, I uploaded the same version but with debug information printed out when trying to load the message catalog and with the catalog files separate from format.exe.
https://github.com/FDOS/format/releases/download/v0.92/format-092a-test3.zip
When you get a chance, please place the format.exe and language file(s) format.tr / format.fr in the same directory.  Set LANG=TR / LANG=FR and SET NLSPATH= or ensure . is included as one of the paths to search.  You may need to press the pause key to read the messages, but it should show something like 

> catread(.\TR\format, tr) 
> Unable to open file  
> catread(.\FORMAT.TR, tr) 
> CATGETS catalog loaded!

**Comment by cardpuncher** [comment]
I did a SET NLSPATH=C:\FREEDOS\BIN\FORMAT where the archive was extracted. When I try to launch format in a setup in Turkish, I get a "No valid message catalog found!" error. For details, please see the screenshot below.

format_tr

**Comment by PerditionC** [comment]
from your screenshot, it is not clear why it isn't finding the catalog.   I'm going to try some more testing on my computer,  but I will probably need to add some more debug output and have you run it again.   Thank you for your help with this.

**Comment by PerditionC** [comment]
Please try https://github.com/FDOS/format/releases/download/v0.92/format-0.92a-test4.zip
The issue is that format has a lot of messages and the size of the message block was larger than available near memory.  I reworked kitten.c so it uses less memory (at the expense of being slower) on loading the catalog file, thus freeing up enough that it should work now.  I will probably switch the release to use compact memory model instead of small so the messages are stored in far heap instead of near heap.  I don't want to introduce explicit far pointers to kitten's catgets if not necessary.

The zip has the messages as individual catalog files or as a single format.msg for all 3 languages.  The search order is format.exe, then %NLSPATH%\%LANG%\FORMAT, %NLSPATH%\FORMAT.%LANG%, and finally %NLSPATH%\FORMAT.MSG -- The files can be left external or you can append the catalog to format:

> COPY /B FORMAT.EXE + FORMAT.NN FORMATNN.EXE

**Comment by cardpuncher** [comment]
That worked, thank you. I simply set the NLSPATH to the directory containing the unzipped archive. French would definitely need some adjustments in order to fit in the screen, I wonder whether empty keys would help.

Also, when I tried 
`COPY /B FORMAT.EXE + FORMAT.FR FORMATFR.EXE`
and then launched formatfr.exe, I got a Jemm386 exception. No idea what that means, please see the screenshot below for more information.

formatfr

**Comment by PerditionC** [comment]
Does the error occur after rebooting? either repeatable or intermittent?  Does it still occur with test6?

**Comment by cardpuncher** [comment]
On 6.09.2024 03:10, Kenneth J Davis wrote:
> Does the error occur after rebooting? either repeatable or intermittent? 
> Does it still occur with test6?

Yes, it still occurs after rebooting, it's always repeatable and still 
occur with test6. My setup is with VirtualBox Version 7.0.16_Ubuntu r162802.

**Pull request merged**
